#!/usr/bin/env bash
# Using a while loop to iterate from 1 to 20
i=1
while ((i <= 20)); do
    case $i in
        4)
            echo "$i and then bad luck from China"
            ;;
        9)
            echo "$i and then bad luck from Japan"
            ;;
        17)
            echo "$i and then bad luck from Italy"
            ;;
        *)
            echo "$i"
            ;;
    esac
    ((i++))
done
