#!/usr/bin/env bash
# Using a while loop to iterate from 1 to 20
i=1
while ((i <= 20)); do
    if ((i == 4)); then
        echo "bad luck from China"
    elif ((i == 9)); then
        echo "bad luck from Japan"
    elif ((i == 17)); then
        echo "bad luck from Italy"
    else
        echo "$i"
    fi
    ((i++))
done
