#!/usr/bin/env bash
# Using a for loop to display the content of the current directory
for file in *; do
    # Check if the file is not hidden and is a regular file
    if [[ ! $file == .* && -f $file ]]; then
        # Extract the part of the name after the first dash
        part_after_dash=$(echo "$file" | cut -d'-' -f2-)

        # Display the result in a list format
        echo "- $part_after_dash"
    fi
done
