#!/usr/bin/env bash
# Specify the file name
file="school"

# Check if the file exists
if [ -e "$file" ]; then
    echo "school file exists"
    
    # Check if the file is empty
    if [ -s "$file" ]; then
        echo "school file is empty"
        
        # Check if the file is a regular file
        if [ -f "$file" ]; then
            echo "school is a regular file"
        fi
    else
        echo "school file is not empty"
    fi
else
    echo "school file does not exist"
fi
