#!/usr/bin/env bash
# Specify the file name
file="school"

# Check if the file exists
if [ -e "$file" ]; then
    echo "$file exists"
    
    # Check if the file is empty
    if [ -s "$file" ]; then
        echo "$file is not empty"
        
        # Check if the file is a regular file
        if [ -f "$file" ]; then
            echo "$file is a regular file"
        fi
    else
        echo "$file is empty"
    fi
else
    echo "$file does not exist"
fi
